name: jira-automation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.11
  - pip
  - pip:
      - numpy==1.23
      - pandas==1.0.4
      - pyyaml
      - jira==3.4.1
      - python-gitlab
      - gspread==4.0.1
      - oauth2client==4.1.3
      - fastapi==0.89.1
      - uvicorn==0.16.0
      - gunicorn==20.1.0
      - google-cloud-bigquery
